name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & Install SDK components (API 34)
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install             "platforms;android-34"             "build-tools;34.0.0"             "platform-tools"

      - name: Configure local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          if [ -n "${{ secrets.GRAPHOPPER_API_KEY }}" ]; then
            echo "GRAPHOPPER_API_KEY=${{ secrets.GRAPHOPPER_API_KEY }}" >> local.properties
          fi
      - name: Ensure AndroidX flags
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      - name: Build with Gradle (managed)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          arguments: |
            --stacktrace
            --warning-mode all
            --no-daemon
            --console=plain
            clean
            :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OsmNav-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload build reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            **/build/reports/**
            **/build/outputs/logs/**
