name: Android CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: |
          sdkmanager --install \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "platform-tools"

      # Optional: write your GraphHopper key from a GitHub secret into local.properties
      - name: Configure local.properties
        run: |
          echo "GRAPHOPPER_API_KEY=${{ secrets.GRAPHOPPER_API_KEY }}" >> local.properties

      # Build using a managed Gradle (no wrapper in repo)
      - name: Build with Gradle (managed)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9
          arguments: assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OsmNav-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # If build fails, also upload the Gradle build reports/logs
      - name: Upload build reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: |
            **/build/reports/**
            **/build/outputs/logs/**
